### ISSUE TITLE
How I can deactivate this feature on several pages?

### ISSUE THREAD

**Issue by antohabio** [SemanticMediaWiki/SemanticBreadcrumbLinks#29]
### Setup and configuration

- SMW version:
- SBL version:
- MW version:
- DB (MySQL etc.):

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

**Comment by kghbln** [comment]
This is currently not possible. A behaviour switch like `__NOBREADCRUMBS__` will be needed to achieve this. This could indeed be useful on some pages like e.g. "Main_Page". So far I only needed to do this there and used CSS for it: 
```CSS
body.mediawiki.ltr.sitedir-ltr.ns-0.ns-subject.page-Main_Page.rootpage-Main_Page.skin-foreground.action-view.approvedRevs-noapprovedrev div#page-content div.row div#p-cactions.large-12.columns div#content div#bodyContent.mw-bodytext div#sbl-breadcrumbs.sbl-breadcrumb-trail-light-boxed {
    display: none;
}
```
Note that this wiki is using the Foreground skin as well as the Approved Revisions extension. However you may very well get the idea.

 If you would like to deacivate on a namespace level you would remove the search pattern from the `egSBLPropertySearchPatternByNamespace` configuration parameter but that's not the question here.
